### ISSUE TITLE
Messages on IM are grouped automatically in one

### ISSUE THREAD

**Issue by Kamahl19** [phpBB-Social-Network/phpBB-Social-Network#65] opened 2012-10-11 11:08 UTC
http://phpbbsocialnetwork.com/viewtopic.php?f=44&t=4152

**Comment by Culprit-CZ** [comment] 2012-10-11 18:43
Who will make it? I have no IDEA how to solve it.

**Comment by balboag** [comment] 2012-10-14 20:10
It is related with more than 1 tab opened, but I dont know more, sorry.

**Comment by senky** [comment] 2012-10-15 15:02
Milestone removed, see: http://phpbbsocialnetwork.com/viewtopic.php?p=17858#p17858

**Comment by senky** [comment] 2013-02-19 16:37
Duplicate of #141.

**Closed as completed by senky** 2013-02-19 16:37 UTC
Labels: bug
