### ISSUE TITLE
Resize textarea only for status

### ISSUE THREAD

**Issue by Kamahl19** [phpBB-Social-Network/phpBB-Social-Network#68] opened 2012-10-11 13:10 UTC
Comment textarea should not be resized when you click on it

**Comment by senky** [comment] 2012-10-11 19:27
This was not properly discussed, link to topic is missing. I do not like you create issues before we all agree on it...

**Comment by Kamahl19** [comment] 2012-10-11 21:46
I would say this is a bug because before 0.7.0 we agreed on resizing status textarea when focused, however culprit made it for comments too, but noone like it on comments

**Comment by senky** [comment] 2012-10-12 05:33
So why it is marked as improvement, if it is bug?

**Comment by balboag** [comment] 2012-10-18 19:47
+1 to this

**Comment by senky** [comment] 2012-12-13 21:51
This is duplicate of #142. I will close this one, as #142 is comment-free and contains link to site.

**Closed as completed by senky** 2012-12-13 21:51 UTC
Labels: change
