### ISSUE TITLE
jQuery UI classes for Profile page to HTML

### ISSUE THREAD

**Issue by Culprit-CZ** [phpBB-Social-Network/phpBB-Social-Network#61] opened 2012-10-10 18:54 UTC
JQuery UI classes should be places directly into Profile page templates

> http://phpbbsocialnetwork.com/viewtopic.php?f=62&t=4216

**Comment by senky** [comment] 2012-10-12 10:34
This is duplicate of #63.

**Closed as completed by senky** 2012-10-12 10:34 UTC
Labels: bug, new
